server:
  port: 8080

spring:
  application:
    name: demo-spring
  datasource:
    url: jdbc:mysql://localhost:3307/nhom9_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 040904
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
